### PR TITLE
Comparison Mode Updates for Calculating/Displaying Percent Diff

### PR DESCRIPTION
**Pull request by kdiluca**
This PR completes the first 4 needs for issue #108.
Contains the following updates:
- a UI widget to turn on comparison 
- mode calculate percentage difference between weekly/historical speed and reference speed
- change segment coloring on map to display speed percentage over/under
- modify UI map legend
- if speed is null, we only show 0 percent diff in the route-info bubble; we also color percent diff as gray if no speed

### CODE REVIEW

**Comment by drewda** [comment]
@kdiluca this looks great when I run a "route" query. But when I run a "region" query, I don't see any segments on the map. Are you able to run "region" queries locally?

**Comment by kdiluca** [comment]
Hmm...I just updated locally, stopped and restarted npm again and re-tried the "range" query and all returns as expected for me.  @mkong0216 are you seeing any weirdnesses with the last round of commits?

**Comment by drewda** [comment]
I just tried locally and it /is/ working for me.

For some reason, it does not work using the build at https://deploy-preview-157--opentraffic-ui.netlify.com/

@kdiluca @mkong0216 do feel free to go ahead and merge and we can check on http://analyst.opentraffic.io/ and further fix if need be afterwards.

**Comment by kdiluca** [comment]
@drewda I see now what you mean.  I just merged the PR in this morning and seeing:
 tangram.min.js:18 Tangram v0.13.5 [error]: Style.parseFeature: style parsing error {type: "Feature", geometry: {…}, properties: {…}} {order: 500, width: 47.99999999999999, next_width: 3.9999999999999973} ReferenceError: e is not defined
Peter and I are looking into it.

**Comment by drewda** [comment]
@kdiluca O.K., thanks for the update and for investigating.

**Comment by kdiluca** [comment]
@drewda , thanks to Brett & Peter, they pointed out that we need to be using es5 syntax instead of es6.  I also wrapped the javascript functions within the tangram-scene file in back ticks to make sure they stay strings and don't get compiled.  The range queries should work now!

**Pull request merged**
